#pragma once

#include "sly/global.h"

namespace sly {
    namespace gfx {
        ENUM_DECL(ePrimitiveType,  
            ePrimitiveType_PointList,
            ePrimitiveType_LineList,
            ePrimitiveType_LineStrip,
            ePrimitiveType_TriangleList,
            ePrimitiveType_TriangleStrip,
            ePrimitivetype_LineList_Adj,
            ePrimitivetype_LineStrip_Adj,
            ePrimitivetype_TriangleList_Adj,
            ePrimitivetype_TriangleStrip_Adj,
            ePrimitivetype_1_Control_Point_Patchlist,
            ePrimitivetype_2_Control_Point_Patchlist,
            ePrimitivetype_3_Control_Point_Patchlist,
            ePrimitivetype_4_Control_Point_Patchlist,
            ePrimitivetype_5_Control_Point_Patchlist,
            ePrimitivetype_6_Control_Point_Patchlist,
            ePrimitivetype_7_Control_Point_Patchlist,
            ePrimitivetype_8_Control_Point_Patchlist,
            ePrimitivetype_9_Control_Point_Patchlist,
            ePrimitivetype_10_Control_Point_Patchlist,
            ePrimitivetype_11_Control_Point_Patchlist,
            ePrimitivetype_12_Control_Point_Patchlist,
            ePrimitivetype_13_Control_Point_Patchlist,
            ePrimitivetype_14_Control_Point_Patchlist,
            ePrimitivetype_15_Control_Point_Patchlist,
            ePrimitivetype_16_Control_Point_Patchlist,
            ePrimitivetype_17_Control_Point_Patchlist,
            ePrimitivetype_18_Control_Point_Patchlist,
            ePrimitivetype_19_Control_Point_Patchlist,
            ePrimitivetype_20_Control_Point_Patchlist,
            ePrimitivetype_21_Control_Point_Patchlist,
            ePrimitivetype_22_Control_Point_Patchlist,
            ePrimitivetype_23_Control_Point_Patchlist,
            ePrimitivetype_24_Control_Point_Patchlist,
            ePrimitivetype_25_Control_Point_Patchlist,
            ePrimitivetype_26_Control_Point_Patchlist,
            ePrimitivetype_27_Control_Point_Patchlist,
            ePrimitivetype_28_Control_Point_Patchlist,
            ePrimitivetype_29_Control_Point_Patchlist,
            ePrimitivetype_30_Control_Point_Patchlist,
            ePrimitivetype_31_Control_Point_Patchlist,
            ePrimitivetype_32_Control_Point_Patchlist,
            ePrimitiveType_Max,
            ePrimitiveType_Default = ePrimitiveType_TriangleList
        );
        ENUM_DECL(ePrimitiveTopologyType,  
            ePrimitiveTopologyType_Point,
            ePrimitiveTopologyType_Line,
            ePrimitiveTopologyType_Triangle,
            ePrimitiveTopologyType_Patch,
            ePrimitiveTopologyType_Max,
            ePrimitiveTopologyType_Default = ePrimitiveTopologyType_Triangle
        );

        /*D3D_PRIMITIVE_TOPOLOGY_UNDEFINED	= 0,
        D3D_PRIMITIVE_TOPOLOGY_POINTLIST	= 1,
        D3D_PRIMITIVE_TOPOLOGY_LINELIST	= 2,
        D3D_PRIMITIVE_TOPOLOGY_LINESTRIP	= 3,
        D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST	= 4,
        D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP	= 5,
        D3D_PRIMITIVE_TOPOLOGY_LINELIST_ADJ	= 10,
        D3D_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ	= 11,
        D3D_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ	= 12,
        D3D_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ	= 13,
        D3D_PRIMITIVE_TOPOLOGY_1_CONTROL_POINT_PATCHLIST	= 33,
        D3D_PRIMITIVE_TOPOLOGY_2_CONTROL_POINT_PATCHLIST	= 34,
        D3D_PRIMITIVE_TOPOLOGY_3_CONTROL_POINT_PATCHLIST	= 35,
        D3D_PRIMITIVE_TOPOLOGY_4_CONTROL_POINT_PATCHLIST	= 36,
        D3D_PRIMITIVE_TOPOLOGY_5_CONTROL_POINT_PATCHLIST	= 37,
        D3D_PRIMITIVE_TOPOLOGY_6_CONTROL_POINT_PATCHLIST	= 38,
        D3D_PRIMITIVE_TOPOLOGY_7_CONTROL_POINT_PATCHLIST	= 39,
        D3D_PRIMITIVE_TOPOLOGY_8_CONTROL_POINT_PATCHLIST	= 40,
        D3D_PRIMITIVE_TOPOLOGY_9_CONTROL_POINT_PATCHLIST	= 41,
        D3D_PRIMITIVE_TOPOLOGY_10_CONTROL_POINT_PATCHLIST	= 42,
        D3D_PRIMITIVE_TOPOLOGY_11_CONTROL_POINT_PATCHLIST	= 43,
        D3D_PRIMITIVE_TOPOLOGY_12_CONTROL_POINT_PATCHLIST	= 44,
        D3D_PRIMITIVE_TOPOLOGY_13_CONTROL_POINT_PATCHLIST	= 45,
        D3D_PRIMITIVE_TOPOLOGY_14_CONTROL_POINT_PATCHLIST	= 46,
        D3D_PRIMITIVE_TOPOLOGY_15_CONTROL_POINT_PATCHLIST	= 47,
        D3D_PRIMITIVE_TOPOLOGY_16_CONTROL_POINT_PATCHLIST	= 48,
        D3D_PRIMITIVE_TOPOLOGY_17_CONTROL_POINT_PATCHLIST	= 49,
        D3D_PRIMITIVE_TOPOLOGY_18_CONTROL_POINT_PATCHLIST	= 50,
        D3D_PRIMITIVE_TOPOLOGY_19_CONTROL_POINT_PATCHLIST	= 51,
        D3D_PRIMITIVE_TOPOLOGY_20_CONTROL_POINT_PATCHLIST	= 52,
        D3D_PRIMITIVE_TOPOLOGY_21_CONTROL_POINT_PATCHLIST	= 53,
        D3D_PRIMITIVE_TOPOLOGY_22_CONTROL_POINT_PATCHLIST	= 54,
        D3D_PRIMITIVE_TOPOLOGY_23_CONTROL_POINT_PATCHLIST	= 55,
        D3D_PRIMITIVE_TOPOLOGY_24_CONTROL_POINT_PATCHLIST	= 56,
        D3D_PRIMITIVE_TOPOLOGY_25_CONTROL_POINT_PATCHLIST	= 57,
        D3D_PRIMITIVE_TOPOLOGY_26_CONTROL_POINT_PATCHLIST	= 58,
        D3D_PRIMITIVE_TOPOLOGY_27_CONTROL_POINT_PATCHLIST	= 59,
        D3D_PRIMITIVE_TOPOLOGY_28_CONTROL_POINT_PATCHLIST	= 60,
        D3D_PRIMITIVE_TOPOLOGY_29_CONTROL_POINT_PATCHLIST	= 61,
        D3D_PRIMITIVE_TOPOLOGY_30_CONTROL_POINT_PATCHLIST	= 62,
        D3D_PRIMITIVE_TOPOLOGY_31_CONTROL_POINT_PATCHLIST	= 63,
        D3D_PRIMITIVE_TOPOLOGY_32_CONTROL_POINT_PATCHLIST	= 64,   */     
    }
}