#pragma once

#include "sly/global.h"
#include "sly/gfx/enums/blendlogicoperation.h"
#include "sly/gfx/enums/blendoperation.h"
#include "sly/gfx/enums/blendtype.h"
#include "sly/gfx/enums/comparefunction.h"
#include "sly/gfx/enums/depthwritemask.h"
#include "sly/gfx/enums/indexbufferstripcutvalue.h"
#include "sly/gfx/enums/polygoncullmode.h"
#include "sly/gfx/enums/polygonfillmode.h"
#include "sly/gfx/enums/stenciloperation.h"
#include "sly/gfx/enums/dataformat.h"
#include "sly/gfx/enums/datainputclassification.h"
#include "sly/gfx/enums/primitivetype.h"